spring:
  application:
    name: coffee-shop
  profiles:
    active:
    - mysql
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    io.learning.coffeeshop: DEBUG